export const FETCHING = "FETCHING";
export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_ERROR = "FETCH_ERROR";

export const SET_SEARCHING_YEAR = "SET_SEARCHING_YEAR";
export const SET_SEARCHING_TYPE = "SET_SEARCHING_TYPE";